apiVersion: v1
kind: Secret
metadata:
  name: my-app-secrets
type: Opaque
data:
  spring.datasource.password: ZjFzM3J2XzE=  # Base64 encoded "f1s3rv_1"
  spring.datasource.username: YXBlcmlvaGF0cw==  # Base64 encoded "aperiohats"

