apiVersion: autoscaling/v1
kind: HorizontalPodAutoscaler
metadata:
  name: data-service-hpa
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: data-service-deployment
  minReplicas: 3
  maxReplicas: 10
  targetCPUUtilizationPercentage: 80
