apiVersion: v1
kind: PersistentVolume
metadata:
  name: bootcamp-nfs-pv
spec:
  capacity:
    storage: 10Gi
  accessModes:
    - ReadWriteMany
  persistentVolumeReclaimPolicy: Retain
  storageClassName: nfs
  mountOptions:
    - vers=3
  nfs:
    path: /bootcamp
    server: 10.1.40.252

