apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: bootcamp-nfs-pvc
spec:
  accessModes:
    - ReadWriteMany
  storageClassName: nfs
  resources:
    requests:
      storage: 5Gi  # Adjust as per your needs

