apiVersion: v1
kind: ConfigMap
metadata:
  name: my-app-config
data:
  spring.datasource.url: jdbc:as400://10.1.40.25;libraries=B800DD2W
  spring.datasource.driver-class-name: com.ibm.as400.access.AS400JDBCDriver
  spring.jpa.properties.hibernate.dialect: org.hibernate.dialect.DB2Dialect
  spring.jpa.hibernate.naming.implicit-strategy: org.hibernate.boot.model.naming.ImplicitNamingStrategyLegacyJpaImpl
  spring.jpa.hibernate.naming.physical-strategy: org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl
  spring.jpa.show-sql: "true"
  spring.jpa.hibernate.ddl-auto: none
  logging.level.org.springframework.web: INFO
  logging.level.root: INFO
  server.port: "8080"

