apiVersion: apps/v1
kind: Deployment
metadata:
  name: fiserv-notify-deployment
  namespace: bootcamp
spec:
  replicas: 1
  selector:
    matchLabels:
      app: fiserv-notify
  template:
    metadata:
      labels:
        app: fiserv-notify
    spec:
      containers:
      - name: fiserv-notify-container
        image: docker.io/jeregatong/notify:0.0.14
        ports:
          - containerPort: 8888

---
apiVersion: v1
kind: Service
metadata:
  name: fiserv-notify-service
  namespace: bootcamp
spec:
  selector:
    app: fiserv-notify
  ports:
  - protocol: TCP
    port: 8888
    targetPort: 8888
  type: NodePort
